use_frameworks!

platform :ios, '8.0'

target 'YBPlayerRotationManage_Example' do
  pod 'YBPlayerRotationManage', :path => '../'

  target 'YBPlayerRotationManage_Tests' do
    inherit! :search_paths

    
  end
end
